In [1]:
# Name  : Priyanshu jha
# Reg   : BL.EN.U4CSE21165
# sec   : CSE-B
# Sub   : Machine Learning
# Lab   : 07

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import svm
print("Import successfull :)")

Import successfull :)


In [2]:
dataset = pd.read_csv(r"C:\Users\admin\Documents\ML\Lab06\faces.csv")
print(dataset.head())

     image_name  width  height   x0   y0    x1   y1
0  00001722.jpg   1333    2000  490  320   687  664
1  00001044.jpg   2000    1333  791  119  1200  436
2  00001050.jpg    667    1000  304  155   407  331
3  00001736.jpg    626     417  147   14   519  303
4  00003121.jpg    626     418  462   60   599  166


In [3]:
#A1. Train a support vector machine using the training set obtained from above exerciseyou’re yourdataset has multiple classes,
#take any two classes for this exercis

from sklearn.model_selection import train_test_split
X = dataset[['x0','y0','x1','y1']]
y = dataset['y1']
X_train,X_test, y_train,y_test = train_test_split(X,y,test_size=0.2)


In [4]:
clf = svm.SVC()
clf.fit(X_train,y_train)

SVC()

In [5]:
# Getting the support vetors
clf.support_vectors_

array([[4.800e+01, 1.000e+00, 9.800e+01, 4.800e+01],
       [1.500e+01, 5.000e+00, 5.200e+01, 5.000e+01],
       [1.500e+01, 5.000e+00, 5.200e+01, 5.000e+01],
       ...,
       [2.145e+03, 1.749e+03, 3.748e+03, 2.993e+03],
       [5.212e+03, 2.211e+03, 6.815e+03, 3.455e+03],
       [4.860e+02, 1.032e+03, 2.500e+03, 4.471e+03]])

In [6]:
# A2. Test the accuracy of the SVM using the test set obtained from above 
# exercise. Following code for help
clf.score(X_test,y_test)

0.0029850746268656717

In [28]:
clf.fit(X_train,y_train)

SVC()

In [29]:
#  Use the Predict function of SVC classifier to study the output values of the classifier.
y_pred = clf.predict(X_test)

In [37]:
# testing the predicting values 
from sklearn.metrics import confusion_matrix,f1_score,accuracy_score,recall_score,precision_score
accuracy = accuracy_score(y_test,y_pred)
conf_matrix = confusion_matrix(y_test,y_pred)


In [32]:
print(accuracy)

0.0029850746268656717


In [38]:
print("Confusion matrix\n",conf_matrix)

Confusion matrix
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [40]:
# A4. Experiment with various kernel functions (‘linear’, ‘poly’, ‘rbf’&‘sigmoid’)
#  to train and test the accuracy of the models.

#  Kernel function = linear
clf = svm.SVC(kernel='linear')
clf.fit(X_train,y_train)
y_pred1 = clf.predict(X_test)
accuracy1 = accuracy_score(y_test,y_pred1)

#  Kernel function = poly
clf = svm.SVC(kernel='poly')
clf.fit(X_train,y_train)
y_pred2 = clf.predict(X_test)
accuracy2 = accuracy_score(y_test,y_pred2)


#  Kernel function = sigmoid
clf = svm.SVC(kernel='sigmoid')
clf.fit(X_train,y_train)
y_pred3 = clf.predict(X_test)
accuracy3 = accuracy_score(y_test,y_pred3)

In [41]:
print('Accuracy of SVM by using linear model: ',accuracy1)
print('Accuracy of SVM by using linear model: ',accuracy2)
print('Accuracy of SVM by using linear model: ',accuracy3)

Accuracy of SVM by using linear model:  0.31343283582089554
Accuracy of SVM by using linear model:  0.0029850746268656717
Accuracy of SVM by using linear model:  0.0
